packages:
  - playground
  - templates/*
  - packages/*
catalog:
  '@antfu/ni': ^24.3.0
  '@antfu/utils': ^9.2.0
  '@gabortorma/antfu-eslint-config': ^3.0.1
  '@octokit/rest': ^20.1.1
  '@octokit/types': ^13.10.0
  '@types/node': ^22.15.12
  c12: 3.0.3
  change-case: ^5.4.4
  citty: ^0.1.6
  compare-versions: ^6.1.1
  consola: ^3.4.2
  defu: ^6.1.4
  dotenv-cli: ^8.0.0
  jiti: ^2.4.2
  pkg-types: ^2.1.0
  pnpm: ^10.10.0
  release-it: ^19.0.2
  release-it-pnpm: ^4.6.5
  replace-in-file: ^8.3.0
  simple-git: ^3.27.0
  typescript: ^5.8.3
  unbuild: ^3.5.0
  vitest: ^3.1.3
  workspace-tools: ^0.38.4
